# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4762286d4d94ea408f9c3a60e3547673a13064a765d89e93b8946ca0ad4feed0ca02aa665e8360061fc8ac5f8bf811f28a83d45de0d3a258e7c0cfe7ac8cae

test:
  secret_key_base: de843bc7dd8fd0717fb3cfe5545b848d3f1814c61fa9207e1ef5316461f18149319c7086e7c57001c3b9455bb4dda315f2b7fcd0e447982028a4b180eba80d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
